apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: yoyoyaya-ceaee-certificate
  namespace: yoyoyaya-ceaee
spec:
  secretName: yoyoyaya-ceaee-secret-tls
  commonName: thanak81-yoyoyaya.assessify.org
  dnsNames:
  - thanak81-yoyoyaya.assessify.org
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
